language: java
jdk:
  - oraclejdk7
  - openjdk7
install: mvn install -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6 -DskipTests=true -B
script: mvn test -Dmaven.compiler.target=1.6 -Dmaven.compiler.source=1.6 -B